/**
 * This code was generated by Builder.io
 */
import React from "react";
// import Sidebar from "../Components/Sidebar";
import FilterSection from "../components/FilterSection";
import PendingWOsTable from "../../services/PendingWorkOrders/PendingWOsTable";

function PendingWOsPage() {
  return (
    <div className="flex flex-col min-h-screen bg-white">
      <PendingWOsTable />
    </div>
  );
}

export default PendingWOsPage;
