/**
 * This code was generated by Builder.io
 */
import React from "react";

import PendingWOsTable from "../../services/PendingWorkOrders/PendingWOsTable";

function PendingWorkOrdersPage() {
  return (
    <div className="flex flex-col min-h-screen bg-white">
      <PendingWOsTable />
    </div>
  )
}

export default PendingWorkOrdersPage;
